---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: mango-bootc
description: This is my personal OS image of Mango and Fedora using bootc.

base-image: quay.io/fedora/fedora-bootc
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        add:
          - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
          - https://forgejo.jtekk.dev/api/packages/TekkRPM/rpm/tekk-fedora-%OS_VERSION%.repo
          - terra.repo
      copr:
        - atim/starship
        - ilyaz/LACT
      nonfree: rpmfusion
    install:
      packages:
        - micro
        - starship

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install:
          - com.bitwarden.desktop 
          - io.github.kolunmi.Bazaar
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing
