---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nelhua-mango
description: This is my personal OS image of Mango and Fedora, built on the BlueBuild base.

# base-image: ghcr.io/blue-build/base-images/fedora-base
base-image: quay.io/fedora/fedora-bootc:rawhide
image-version: latest

modules:
  - from-file: all-packages.yml
  - type: os-release
    properties:
      PRETTY_NAME: Nelhua-Linux (Mango Edition)
